export const stories = [
  {
    logo: '/images/logo/logo-dev-dads.webp',
    header: 'DEVDADS',
    titlePresentation: 'DEVDADS',
    image: '/images/banner-welcome-to-dev-dads.webp',
    tags: ['Collector Stories', 'NFTs', 'Brand Strategy', 'Marketing', 'Dev Dads'],
    titleDescription: 'About',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae tincidunt dui. Nullam nec neque diam. Ut a quam iaculis, lobortis magna ut, pretium neque.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae tincidunt dui. Nullam nec neque diam. Ut a quam iaculis, lobortis magna ut, pretium neque.',
    price: '123.60',
  },
  {
    logo: '/images/logo/logo-codelambs.webp',
    header: 'CODELAMBS',
    titlePresentation: 'BUILT BY @CALIMEDIA',
    image: '/images/banner-codelambs.webp',
    tags: ['Collector Stories', 'NFTs', 'Brand Strategy', 'Marketing', 'Dev Dads'],
    titleDescription: 'Story',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae tincidunt dui. Nullam nec neque diam. Ut a quam iaculis, lobortis magna ut, pretium neque.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae tincidunt dui. Nullam nec neque diam. Ut a quam iaculis, lobortis magna ut, pretium neque.',
    price: '123.60',
  },
];

export const assets1 = [
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
  { src: '/images/store-asset-4.webp' },
  { src: '/images/store-asset-5.webp' },
];

export const assets2 = [
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-2.webp' },
  { src: '/images/store-asset-3.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-2.webp' },
  { src: '/images/store-asset-3.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-2.webp' },
  { src: '/images/store-asset-3.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-2.webp' },
  { src: '/images/store-asset-3.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-2.webp' },
  { src: '/images/store-asset-3.webp' },
  { src: '/images/store-asset-1.webp' },
  { src: '/images/store-asset-2.webp' },
  { src: '/images/store-asset-3.webp' },
  { src: '/images/store-asset-1.webp' },
];

export const apps1 = [
  { src: '/images/carmel-universe-app-1.webp', description: 'Dimension 98' },
  { src: '/images/carmel-universe-app-2.webp', description: 'Splatches' },
  { src: '/images/carmel-universe-app-1.webp', description: 'Dimension 98' },
  { src: '/images/carmel-universe-app-2.webp', description: 'Splatches' },
  { src: '/images/carmel-universe-app-1.webp', description: 'Dimension 98' },
  { src: '/images/carmel-universe-app-2.webp', description: 'Splatches' },
];

export const creators = [
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
  { photo: '/images/logo/logo-dev-dads.webp', name: 'Dan the Man' },
];
