import Carmel from '~/images/dashboard/Carmel.webp';
import Ethereum from '~/images/dashboard/ETH.webp';

export const activity = [
  {
    action: 'buy',
    asset: 'Ethereum',
    assetIcon: Ethereum,
    assetShort: 'ETH',
    date: '15 June 2023, 07:43 PM',
    value: '1.00',
    fiatValue: '1,023.00',
    swapAsset: null,
    swapIcon: null,
    failed: true,
  },
  {
    action: 'buy',
    asset: 'Ethereum',
    assetIcon: Ethereum,
    assetShort: 'ETH',
    date: '15 June 2023, 07:43 PM',
    value: '1.00',
    fiatValue: '1,023.00',
    swapAsset: null,
    swapIcon: null,
    failed: false,
  },
  {
    action: 'sent',
    asset: 'Ethereum',
    assetIcon: Ethereum,
    assetShort: 'ETH',
    date: '15 June 2023, 07:43 PM',
    value: '1.00',
    fiatValue: '1,023.00',
    swapAsset: null,
    swapIcon: null,
    failed: false,
  },
  {
    action: 'received',
    asset: 'Ethereum',
    assetIcon: Ethereum,
    assetShort: 'ETH',
    date: '15 June 2023, 07:43 PM',
    value: '1.5',
    fiatValue: '1,500.00',
    swapAsset: null,
    swapIcon: null,
    failed: false,
  },
  {
    action: 'swap',
    asset: 'Ethereum',
    assetIcon: Ethereum,
    assetShort: 'ETH',
    date: '15 June 2023, 07:43 PM',
    value: '12,453',
    fiatValue: '1,500.00',
    swapAsset: 'Carmel',
    swapIcon: Carmel,
    failed: false,
  },
];
