import productImage from '../../images/product-image.jpg';
import userPhoto from '../../images/user-64-12.jpg';
import propertyLogo1 from '../../images/propertyLogo1.svg';
import propertyLogo2 from '../../images/propertyLogo2.svg';

export const data = [
  {
    title: 'Intro to Web3 for Entrepreneurs',
    shortDescription: 'Learn ',
    photo: productImage,
    community: 'Genesis',
    userPhoto: userPhoto,
    username: 'Dan',
    property: 'propertyname',
    level: 'Beginner',
    propertyLogo: propertyLogo1,
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Intro to the Carmel Way of working',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    community: 'Genesis',
    username: 'username',
    level: 'Beginner',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-another-concepts-different-slug',
  },
  {
    title: 'Intro to AI for Web3 Entrepreneurs',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    community: 'Genesis',
    level: 'Beginner',
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    propertyLogo: propertyLogo1,
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    username: 'username',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    property: 'propertyname',
    propertyLogo: propertyLogo1,
    username: 'username',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    username: 'username',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    propertyLogo: propertyLogo2,
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    propertyLogo: propertyLogo2,
    username: 'username',
    property: 'propertyname',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    propertyLogo: propertyLogo2,
    property: 'propertyname',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    propertyLogo: propertyLogo2,
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    propertyLogo: propertyLogo2,
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    propertyLogo: propertyLogo2,
    username: 'username',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    property: 'propertyname',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    propertyLogo: propertyLogo2,
    property: 'propertyname',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    propertyLogo: propertyLogo2,
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    propertyLogo: propertyLogo2,
    reward: '341 Meraki',
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    propertyLogo: propertyLogo2,
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    propertyLogo: propertyLogo2,
    property: 'propertyname',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    reward: '341 Meraki',
    property: 'propertyname',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    propertyLogo: propertyLogo2,
    id: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    username: 'username',
    property: 'propertyname',
    reward: '341 Meraki',
    propertyLogo: propertyLogo2,
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    id: '5-basic-concepts-about-variables',
  },
];
