import heroPhoto from '../../images/stories/StoreisHero.webp';
import story1 from '../../images/stories/story1.webp';
import story2 from '../../images/stories/story2.webp';
import userPhoto from '../../images/user-64-12.jpg';
import propertyLogo1 from '../../images/propertyLogo1.svg';

export const storiesData = [
  {
    storyId: 1,
    highlight: true,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Dan',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: heroPhoto,
    slug: 'some-slug-0',
    data: {
      tags: ['Collector Stories', 'NFTs', 'News', 'Crypto'],
      title: 'The biggest drop in Times Square since New Years Eve',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 2,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Andrei',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['Crypto World', 'NFTs', 'News', 'Crypto', 'Web3', 'Bitcoin', 'Invest', 'Business'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 3,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Sasha',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story2,
    slug: 'some-slug-0',
    data: {
      tags: ['Collector Stories', 'NFT Update', 'News', 'Crypto World', 'Web3', 'Bitcoin', 'Invest', 'Business'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 4,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Eduard',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story2,
    slug: 'some-slug-0',
    data: {
      tags: ['Collector Stories', 'NFT Update', 'News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 5,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Dan',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['News', 'Crypto World'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 6,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Dan',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story2,
    slug: 'some-slug-0',
    data: {
      tags: ['Collector Stories', 'NFT Update', 'News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 7,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Jim',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 8,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Dan',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 9,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Radu',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 10,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Lucian',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
  {
    storyId: 11,
    highlight: false,
    authorImageLink: 'https://picsum.photos/300/300',
    userPhoto: userPhoto,
    username: 'Andrei',
    appName: 'cyberapp',
    appLogo: propertyLogo1,
    communityName: 'devdads',
    imageLink: story1,
    slug: 'some-slug-0',
    data: {
      tags: ['News', 'Crypto World', 'Community'],
      title: 'Decentralizing NFT metadata on OpenSea Marketplace',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi officiis obcaecati officia tempore quod magnam suscipit, sunt beatae, velit aperiam, incidunt exercitationem non laboriosam architecto aspernatur odit amet expedita.',
    },
    date: '2021-06-08',
  },
];
