import productImage from '../../images/product-image.jpg';
import userPhoto from '../../images/user-64-12.jpg';
import photo from '../../images/meetup-photo-02.jpg';

export const challengeData = [
  {
    title: 'Learn 5 Basic Concepts Of Blockchain',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do, this is over 155 characters',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '120 Meraki',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: photo,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '120 Meraki',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '120 Meraki',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    info: '120 Meraki',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '120 Meraki',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '120 Meraki',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
  {
    title: 'Learn 5 Basic Concepts About Variables',
    shortDescription:
      'I put this together in an attempt to see if I can get all my kids comfortable with some basic concepts in programming while keeping it fun and simple to do...',
    photo: productImage,
    userPhoto: userPhoto,
    nameTag: 'nametag',
    reward: '341 Meraki',
    info: '5 Lorem Ipsum',
    tagText: 'Conversation',
    slug: '5-basic-concepts-about-variables',
  },
];
